### ISSUE TITLE
Refactor all stateful widgets in the app to use cubits

### ISSUE THREAD

**Issue by boxdot** [phnx-im/infra#268]
The list of cubits that we need to implement to port all functionality from stateful widget to (mostly) stateless widgets:

* [x] `NavigationCubit` -- responsible for the navigation state (a single instance per app) (#242)
* [x] `UserCubit` -- currently logged in user (a single instance per app) (#249)
* [x] `ConversationListCubit` -- state and functionality of the list of conversations (#267)
* [x] `ConversationDetailCubit` -- state and functionality of the details screen of a single conversation (#264)
* [x] `MessageListCubit` -- state and functionality of the message list (#282)
* [x] `MessageCubit` -- state and functionality of a single message (#282)
* [x] `AddMembersCubit` -- state and functionality for adding members to groups (#284)
